### PR TITLE
Update singly_linked_list_exercise.py

### PR DESCRIPTION
**Pull request by Aurelius-673**
I have added two lines of code in line no. 120, so that the loop runs for even the last node.
@groverkds

### CODE REVIEW

**Comment by Aurelius-673** [comment]
I am a freshman at college and hope I have done well!

**Comment by Aurelius-673** [comment]
I am a beginner here and my first update on GitHub, so please give your valuable suggestions!

**Comment by dumbcoder7** [comment]
The PR seems unnecessary. Since, the while loop anyway runs till `iter.next` is not None, there is no reason to add the following block of the code.

Please attach screenshots of examples if found otherwise.

**Review by dumbcoder7 — CHANGES_REQUESTED** [review]
###Not necessary. Consider closing the PR.

**Comment by groverkds** [comment]
I agree to @dumbcoder7, `while iter.next:` would take care of that.

**Pull request closed without merging**
